api_platform:
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        html: [ 'text/html' ]
        multipart: [ 'multipart/form-data' ]

    defaults:
        pagination_items_per_page: 10
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

