vich_uploader:
  db_driver: orm

  mappings:
    file:
      uri_prefix: /api/files
      upload_destination: '%kernel.project_dir%/src/Resource'
      namer: Vich\UploaderBundle\Naming\OrignameNamer
